config/routes.rb
Hw::Application.routes.draw do
  resources :hellos

end

app/models/hello.rb
class Hello < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
  # GET /hellos
  # GET /hellos.json
  def index
    @hellos = Hello.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hellos }
    end
  end

  # GET /hellos/1
  # GET /hellos/1.json
  def show
    @hello = Hello.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hello }
    end
  end

  # GET /hellos/new
  # GET /hellos/new.json
  def new
    @hello = Hello.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hello }
    end
  end

  # GET /hellos/1/edit
  def edit
    @hello = Hello.find(params[:id])
  end

  # POST /hellos
  # POST /hellos.json
  def create
    @hello = Hello.new(params[:hello])

    respond_to do |format|
      if @hello.save
        format.html { redirect_to @hello, notice: 'Hello was successfully created.' }
        format.json { render json: @hello, status: :created, location: @hello }
      else
        format.html { render action: "new" }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hellos/1
  # PUT /hellos/1.json
  def update
    @hello = Hello.find(params[:id])

    respond_to do |format|
      if @hello.update_attributes(params[:hello])
        format.html { redirect_to @hello, notice: 'Hello was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hello.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hellos/1
  # DELETE /hellos/1.json
  def destroy
    @hello = Hello.find(params[:id])
    @hello.destroy

    respond_to do |format|
      format.html { redirect_to hellos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/views/hellos/_form.html.erb
<%= form_for(@hello) do |f| %>
  <% if @hello.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hello.errors.count, "error") %> prohibited this hello from being saved:</h2>

      <ul>
      <% @hello.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hellos/edit.html.erb
<h1>Editing hello</h1>

<%= render 'form' %>

<%= link_to 'Show', @hello %> |
<%= link_to 'Back', hellos_path %>

app/views/hellos/index.html.erb
<h1>Listing hellos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hellos.each do |hello| %>
  <tr>
    <td><%= hello.name %></td>
    <td><%= link_to 'Show', hello %></td>
    <td><%= link_to 'Edit', edit_hello_path(hello) %></td>
    <td><%= link_to 'Destroy', hello, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hello', new_hello_path %>

app/views/hellos/new.html.erb
<h1>New hello</h1>

<%= render 'form' %>

<%= link_to 'Back', hellos_path %>

app/views/hellos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hello.name %>
</p>


<%= link_to 'Edit', edit_hello_path(@hello) %> |
<%= link_to 'Back', hellos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>